ALTER FUNCTION SF_DataCompleta (@DATA DATETIME) 
RETURNS VARCHAR(40) AS
	BEGIN
		DECLARE @DIA INT, @MES VARCHAR(15), @ANO INT, @NOVA_DATA VARCHAR(40)

		SET @DIA = DAY(@DATA)
		SET @MES = DATENAME(MM, @DATA)
		SET @ANO = YEAR(@DATA)

		SET @NOVA_DATA = 'DD de MM de YY'
		SET @NOVA_DATA = REPLACE(@NOVA_DATA, 'DD', STR(@DIA))
		SET @NOVA_DATA = REPLACE(@NOVA_DATA, 'MM', @MES)
		SET @NOVA_DATA = REPLACE(@NOVA_DATA, 'YY', STR(@ANO))

		RETURN @NOVA_DATA
	END

DECLARE @NOVA_DATA VARCHAR(40)
EXEC @NOVA_DATA = SF_DataCompleta '05-04-2009'
PRINT @NOVA_DATA

--------------------------------------------------

CREATE FUNCTION SF_LPAD (@STRING VARCHAR(8000), @TAMANHO INT, @CARACTER CHAR(1)) 
RETURNS VARCHAR(8000)
	BEGIN
		DECLARE @STRING_FORMATADA VARCHAR(8000), @TAMANHO_STRING_FORMATADA INT

		SET @STRING_FORMATADA = LEFT(@STRING, @TAMANHO)
		SET @TAMANHO_STRING_FORMATADA = LEN(@STRING_FORMATADA)
	
		IF (@TAMANHO_STRING_FORMATADA < @TAMANHO)
			BEGIN
				DECLARE @DIFERENCA INT
				SET @DIFERENCA = @TAMANHO - @TAMANHO_STRING_FORMATADA
				DECLARE @LPAD VARCHAR(8000)

				SET @LPAD = LEFT(REPLICATE(@CARACTER, @DIFERENCA),@DIFERENCA)

				SET @STRING_FORMATADA = LEFT(CONCAT(@LPAD, @STRING_FORMATADA), @TAMANHO)
			END

		RETURN @STRING_FORMATADA
	END

DECLARE @STRING VARCHAR(20)
EXEC @STRING = SF_LPAD 'TESTES', 5, 'A' 
PRINT @STRING
PRINT LEN(@STRING)


DECLARE @STRING VARCHAR(20)
EXEC @STRING = SF_LPAD 'TEST', 5, '0' 
PRINT @STRING
PRINT LEN(@STRING)


DECLARE @STRING VARCHAR(20)
EXEC @STRING = SF_LPAD 'TESTE', 5, '0' 
PRINT @STRING
PRINT LEN(@STRING)