CREATE PROCEDURE SP_SALARIO (@ANO INT, @SALARIO NUMERIC(10,2), @REAJUSTE NUMERIC(10,2) OUTPUT) AS

IF (@ANO < 2000)
	BEGIN
		SET @REAJUSTE = @SALARIO + @SALARIO * 0.30 
	END
ELSE IF((@ANO >= 2000) AND (@ANO < 2005))
	BEGIN
		SET @REAJUSTE = @SALARIO + @SALARIO * 0.20
	END
ELSE IF(@ANO >= 2005)
	BEGIN
		SET @REAJUSTE = @SALARIO + @SALARIO * 0.10
	END
	
SELECT @REAJUSTE

ALTER PROCEDURE SP_SALARIO (@ANO INT, @SALARIO NUMERIC(10,2), @REAJUSTE NUMERIC(10,2) OUTPUT) AS
SET @REAJUSTE = @SALARIO
IF (@ANO < 2000)
	BEGIN
		SET @REAJUSTE += @SALARIO * 0.30 
	END
ELSE IF((@ANO >= 2000) AND (@ANO < 2005))
	BEGIN
		SET @REAJUSTE += @SALARIO * 0.20
	END
ELSE IF(@ANO >= 2005)
	BEGIN
		SET @REAJUSTE += @SALARIO * 0.10
	END
	
RETURN (@REAJUSTE)

DECLARE @REAJUSTE NUMERIC(10,2)
EXEC SP_SALARIO 2005, 100, @REAJUSTE

CREATE TABLE  TB_FUNCIONARIO_  (
	 MATRICULA  INT NULL DEFAULT NULL,
	 NM_FUNCIONARIO  VARCHAR(50) NULL DEFAULT NULL,
	 ANO_ADMISSAO  INT NULL DEFAULT NULL,
	 SALARIO  NUMERIC(10,2) NULL DEFAULT NULL
)
;

CREATE PROCEDURE SP_ATUALIZA_SALARIO AS

DECLARE @ANO INT
DECLARE @SALARIO NUMERIC(10,2)
DECLARE @REAJUSTE NUMERIC(10,2)


DECLARE C_SALARIO CURSOR FOR 
	SELECT ANO_ADMISSAO, SALARIO FROM TB_FUNCIONARIO_

OPEN C_SALARIO
FETCH C_SALARIO INTO @ANO, @SALARIO
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		EXECUTE @REAJUSTE = SP_SALARIO @ANO, @SALARIO, @REAJUSTE
		UPDATE TB_FUNCIONARIO_ SET SALARIO = @REAJUSTE WHERE CURRENT OF C_SALARIO
		FETCH C_SALARIO INTO @ANO, @SALARIO
	END

CLOSE C_SALARIO
DEALLOCATE C_SALARIO