CREATE TABLE  TB_FUNCIONARIO  (
	 MATRICULA  INT NOT NULL DEFAULT NULL,
	 NOME  VARCHAR(50) NOT NULL DEFAULT NULL,
	 TELEFONE  VARCHAR(10) NULL DEFAULT NULL,
	 ENDERECO  VARCHAR(50) NULL DEFAULT NULL,
	 SALARIO  NUMERIC(10,2) NULL DEFAULT NULL,
	 PENDENCIA  VARCHAR(10) NULL DEFAULT NULL
)
;

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT TB_FUNCIONARIO_pk
PRIMARY KEY (MATRICULA)

INSERT INTO  TB_FUNCIONARIO  ( MATRICULA ,  NOME ,  TELEFONE ,  ENDERECO ) VALUES (1, 'SEVERINO', '12121212', 'MANOEL MESSIAS');
INSERT INTO  TB_FUNCIONARIO  ( MATRICULA ,  NOME ) VALUES (2, 'JOAO');
INSERT INTO  TB_FUNCIONARIO  ( MATRICULA ,  NOME ,  TELEFONE ,  ENDERECO ,  SALARIO ) VALUES (3, 'CARLOS', '1232300', 'MANOEL GARANGAU', 1200);



CREATE PROCEDURE SP_PENDENCIA AS

DECLARE @TELEFONE VARCHAR(9) 
DECLARE @ENDERECO VARCHAR(40)
DECLARE @SALARIO NUMERIC(10,2)

DECLARE C_PENDENCIA CURSOR FOR
SELECT  TELEFONE, ENDERECO, SALARIO FROM TB_FUNCIONARIO FOR UPDATE OF PENDENCIA
OPEN C_PENDENCIA 
FETCH C_PENDENCIA INTO @TELEFONE, @ENDERECO, @SALARIO
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF( (@TELEFONE IS NULL) OR (@ENDERECO IS NULL) OR (@SALARIO IS NULL) )
			BEGIN	
				UPDATE TB_FUNCIONARIO SET PENDENCIA = 'EXISTE PENDENCIA' WHERE CURRENT OF C_PENDENCIA
			END
		ELSE
			BEGIN
				UPDATE TB_FUNCIONARIO SET PENDENCIA = 'SEM PENDENCIA' WHERE CURRENT OF C_PENDENCIA
			END				
		FETCH C_PENDENCIA INTO @TELEFONE, @ENDERECO, @SALARIO
	END
CLOSE C_PENDENCIA
DEALLOCATE C_PENDENCIA 