-- 1 QUESTAO
CREATE TABLE TB_CLIENTE (
	MATRICULA INT NOT NULL DEFAULT NULL,
	NOME VARCHAR(40) NOT NULL DEFAULT NULL,
	TELEFONE VARCHAR(10) NOT NULL DEFAULT NULL
)

-- 2 QUESTAO
CREATE PROCEDURE SP_INCLUI_CLIENTE(@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(10)) AS
INSERT INTO TB_CLIENTE VALUES(@MATRICULA, @NOME, @TELEFONE)
	
--3 QUESTAO
CREATE PROCEDURE SP_EXCLUI_CLIENTE(@MATRICULA INT) AS
DELETE FROM TB_CLIENTE WHERE  MATRICULA = @MATRICULA

	
-- 4 QUESTAO
ALTER PROCEDURE SP_INCLUI_CLIENTE(@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(10), @MENSAGEM VARCHAR(40) OUTPUT) AS
INSERT INTO TB_CLIENTE VALUES(@MATRICULA, @NOME, @TELEFONE) 
SET @MENSAGEM = 'PROCEDIMENTO CONCLUÍDO'
SELECT @MENSAGEM

ALTER PROCEDURE SP_EXCLUI_CLIENTE(@MATRICULA INT, @MENSAGEM VARCHAR(40) OUTPUT) AS
DELETE FROM TB_CLIENTE WHERE  MATRICULA = @MATRICULA
SET @MENSAGEM = 'PROCEDIMENTO CONCLUÍDO'
SELECT @MENSAGEM	

-- 5 QUESTAO
CREATE PROCEDURE SP_ALTERA_CLIENTE(@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(40), @MENSAGEM VARCHAR(100) OUTPUT) AS
UPDATE "TB_CLIENTE" SET "NOME"=@NOME, "TELEFONE"=@TELEFONE
WHERE "MATRICULA"=@MATRICULA 
SET @MENSAGEM = 'PROCEDIMENTO CONCLUÍDO. VARIÁVEIS: '+ @NOME+' '+ @TELEFONE
SELECT @MENSAGEM


-- 6 QUESTAO:
ALTER PROCEDURE SP_ALTERA_CLIENTE(@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(40), @MENSAGEM VARCHAR(100) OUTPUT) AS
IF (@NOME IS NOT NULL) 
	BEGIN
		UPDATE "TB_CLIENTE" SET "NOME"=@NOME 
		WHERE "MATRICULA"=@MATRICULA
	END 
IF (@TELEFONE IS NOT NULL) 
	BEGIN 
		UPDATE "TB_CLIENTE" SET "TELEFONE"=@TELEFONE 
		WHERE "MATRICULA"=@MATRICULA
	END
	
SET @MENSAGEM = 'PROCEDIMENTO CONCLUÍDO.'
SELECT @MENSAGEM