//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControleCliente
    {
        public int idCliente { get; set; }
        public int idHospedagem { get; set; }
        public System.DateTime dataCadastro { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Hospedagem Hospedagem { get; set; }
    }
}
