//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPagamento
    {
        public FormaPagamento()
        {
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int idFormaPagamento { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public int numeroMaximoParcela { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
