//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAcesso
    {
        public int idHistoricoAcesso { get; set; }
        public int idUsuario { get; set; }
        public int idPacoteHospedagem { get; set; }
        public string observacao { get; set; }
        public System.DateTime dataCadastro { get; set; }
    
        public virtual PacoteHospedagem PacoteHospedagem { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
