//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospedagem
    {
        public Hospedagem()
        {
            this.ControleCliente = new HashSet<ControleCliente>();
            this.Item = new HashSet<Item>();
            this.ControleServico = new HashSet<ControleServico>();
        }
    
        public int idHospedagem { get; set; }
        public int idPacoteHospedagem { get; set; }
        public int idQuarto { get; set; }
        public System.DateTime dataAbertura { get; set; }
        public Nullable<System.DateTime> dataLiberacao { get; set; }
        public string placaVeiculo { get; set; }
        public string observacao { get; set; }
        public decimal valorHospedagem { get; set; }
        public bool aberto { get; set; }
    
        public virtual ICollection<ControleCliente> ControleCliente { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<ControleServico> ControleServico { get; set; }
        public virtual PacoteHospedagem PacoteHospedagem { get; set; }
        public virtual Quarto Quarto { get; set; }
    }
}
