//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbtdinewhotelEntities : DbContext
    {
        public dbtdinewhotelEntities()
            : base("name=dbtdinewhotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<ControleCliente> ControleCliente { get; set; }
        public virtual DbSet<FormaPagamento> FormaPagamento { get; set; }
        public virtual DbSet<Historico> Historico { get; set; }
        public virtual DbSet<HistoricoAcesso> HistoricoAcesso { get; set; }
        public virtual DbSet<Hospedagem> Hospedagem { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<PacoteHospedagem> PacoteHospedagem { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Quarto> Quarto { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
        public virtual DbSet<TipoQuarto> TipoQuarto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ControleServico> ControleServico { get; set; }
    }
}
