//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int idItem { get; set; }
        public int idHospedagem { get; set; }
        public int idProduto { get; set; }
        public int quantidade { get; set; }
        public decimal valorTotal { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool cancelado { get; set; }
    
        public virtual Hospedagem Hospedagem { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
