//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacoteHospedagem
    {
        public PacoteHospedagem()
        {
            this.HistoricoAcesso = new HashSet<HistoricoAcesso>();
            this.Hospedagem = new HashSet<Hospedagem>();
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int idPacoteHospedagem { get; set; }
        public decimal valorTotal { get; set; }
        public decimal subTotal { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> dataLiberacao { get; set; }
        public System.DateTime dataEntrada { get; set; }
        public Nullable<System.DateTime> dataSaida { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool ativo { get; set; }
        public string tipoPacote { get; set; }
    
        public virtual ICollection<HistoricoAcesso> HistoricoAcesso { get; set; }
        public virtual ICollection<Hospedagem> Hospedagem { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
