//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int numeroParcela { get; set; }
        public int idFormaPagamento { get; set; }
        public int idPacoteHospedagem { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public System.DateTime dataPrevista { get; set; }
        public Nullable<System.DateTime> dataPagamento { get; set; }
        public decimal valorParcela { get; set; }
        public string status { get; set; }
    
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual PacoteHospedagem PacoteHospedagem { get; set; }
    }
}
