//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarto
    {
        public Quarto()
        {
            this.Hospedagem = new HashSet<Hospedagem>();
        }
    
        public int idQuarto { get; set; }
        public int idTipoQuarto { get; set; }
        public string descricao { get; set; }
        public int capacidade { get; set; }
        public bool ativo { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Hospedagem> Hospedagem { get; set; }
        public virtual TipoQuarto TipoQuarto { get; set; }
    }
}
