//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoQuarto
    {
        public TipoQuarto()
        {
            this.Quarto = new HashSet<Quarto>();
        }
    
        public int idTipoQuarto { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public decimal valor { get; set; }
    
        public virtual ICollection<Quarto> Quarto { get; set; }
    }
}
