//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Historico = new HashSet<Historico>();
            this.HistoricoAcesso = new HashSet<HistoricoAcesso>();
        }
    
        public int idUsuario { get; set; }
        public int idFuncionario { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool ativo { get; set; }
        public string nivelAcesso { get; set; }
    
        public virtual ICollection<Historico> Historico { get; set; }
        public virtual ICollection<HistoricoAcesso> HistoricoAcesso { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
