
ALTER FUNCTION SF_TO_DATE (@DATA VARCHAR(32), @MASCARA VARCHAR(32))
RETURNS DATETIME
AS
BEGIN
	DECLARE @DATA_RETORNO DATETIME,
				@ANO VARCHAR(4),
				@MES VARCHAR(2),
				@DIA VARCHAR(2),
				@HORA VARCHAR(2),
				@SEGUNDO VARCHAR(2),
				@MINUTO VARCHAR(2),
				@INDICE INT
	SET @ANO = '00'
	SET @MES = '00'
	SET @DIA = '00'
	SET @HORA = '00'
	SET @SEGUNDO = '00'
	SET @MINUTO = '00'
	IF (CHARINDEX ('YYYY',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('YYYY',@MASCARA)
		SET @ANO = SUBSTRING(@DATA, @INDICE, (@INDICE+4))
	END
	IF (CHARINDEX ('MM',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('MM',@MASCARA)
		SET @MES = SUBSTRING(@DATA, @INDICE, (@INDICE+2))
	END
	IF (CHARINDEX ('DD',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('DD',@MASCARA)
		SET @DIA = SUBSTRING(@DATA, @INDICE, (@INDICE+2))
	END
	IF (CHARINDEX ('HH',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('HH',@MASCARA)
		SET @HORA = SUBSTRING(@DATA, @INDICE, (@INDICE+2))
	END
	IF (CHARINDEX ('MI',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('MI',@MASCARA)
		SET @MINUTO = SUBSTRING(@DATA, @INDICE, (@INDICE+2))
	END
	IF (CHARINDEX ('SS',@MASCARA) > 0)
	BEGIN
		SET @INDICE = CHARINDEX ('SS',@MASCARA)
		SET @SEGUNDO = SUBSTRING(@DATA, @INDICE, (@INDICE+2))
	END
	DECLARE @DATA_COMPLETA VARCHAR(38)
	IF(@ANO = '00' AND @DIA = '00' AND @MES = '00')
		SET @DATA_COMPLETA = @HORA+':'+@MINUTO+':'+@SEGUNDO
	ELSE
		SET @DATA_COMPLETA = @ANO +@DIA+ @MES +' '+@HORA+':'+@MINUTO+':'+@SEGUNDO
	SET @DATA_RETORNO = CAST(@DATA_COMPLETA  AS datetime)
RETURN @DATA_RETORNO
END

