
CREATE FUNCTION SF_DATACOMPLETA (@DATA DATETIME)
RETURNS VARCHAR(40)
AS
BEGIN
	DECLARE @DATA_COMPLETA VARCHAR(40)
	SET @DATA_COMPLETA = DATENAME (DD, @DATA) + ' de ' + DATENAME (MM, @DATA)+ ' de '+DATENAME (YY, @DATA)
	RETURN @DATA_COMPLETA
END

SET LANGUAGE ENGLISH
DECLARE @DATA_COMPLETA VARCHAR(40)
EXEC @DATA_COMPLETA = SF_DATACOMPLETA '20130222'
SELECT @DATA_COMPLETA

---------------------

CREATE FUNCTION SF_LPAD(@STRING VARCHAR(8000), @TAMANHO INT, @CARACTER CHAR(1))
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(8000)
	SET @RETORNO = LEFT(@STRING, @TAMANHO)
	SET @RETORNO = REPLICATE(@CARACTER, @TAMANHO-LEN(@RETORNO))+@RETORNO
	RETURN @RETORNO
END

DECLARE @RETORNO VARCHAR(40)
EXEC @RETORNO = SF_LPAD 'tech on the net', 16, 'z'
SELECT @RETORNO
