CREATE PROCEDURE SP_FAIXA_SALARIAL(@CARGO INT, @ESCOLARIDADE INT, @SALARIO NUMERIC(10,2)) AS

DECLARE @CD_CARGO INT
DECLARE @CD_ESCOLARIDADE INT
DECLARE @MENOR_VALOR NUMERIC(10,2)
DECLARE @MAIOR_VALOR NUMERIC(10,2)

DECLARE C_SALARIO CURSOR FOR 
	SELECT FS.CD_CARGO, FS.CD_ESCOLARIDADE, FS.MENOR_VALOR, FS.MAIOR_VALOR FROM TB_FAIXASALARIAL FS

OPEN C_SALARIO
FETCH C_SALARIO INTO @CD_CARGO, @CD_ESCOLARIDADE, @MENOR_VALOR, @MAIOR_VALOR
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		IF((@CARGO = @CD_CARGO) AND (@ESCOLARIDADE = @CD_ESCOLARIDADE))
			BEGIN
				IF((@SALARIO >= @MENOR_VALOR) AND (@SALARIO <= @MAIOR_VALOR))
					BEGIN
						SELECT 'VALIDO'
					END
				ELSE
					BEGIN
						SELECT 'INVALIDO'
					END
			END
		FETCH C_SALARIO INTO @CD_CARGO, @CD_ESCOLARIDADE, @MENOR_VALOR, @MAIOR_VALOR
	END

CLOSE C_SALARIO
DEALLOCATE C_SALARIO

ALTER PROCEDURE SP_FAIXA_SALARIAL(@CARGO INT, @ESCOLARIDADE INT, @SALARIO NUMERIC(10,2), @RETORNO BIT OUTPUT) AS

DECLARE @CD_CARGO INT
DECLARE @CD_ESCOLARIDADE INT
DECLARE @MENOR_VALOR NUMERIC(10,2)
DECLARE @MAIOR_VALOR NUMERIC(10,2)

SET @RETORNO = 0

DECLARE C_SALARIO CURSOR FOR 
	SELECT FS.CD_CARGO, FS.CD_ESCOLARIDADE, FS.MENOR_VALOR, FS.MAIOR_VALOR FROM TB_FAIXASALARIAL FS

OPEN C_SALARIO
FETCH C_SALARIO INTO @CD_CARGO, @CD_ESCOLARIDADE, @MENOR_VALOR, @MAIOR_VALOR
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		IF((@CARGO = @CD_CARGO) AND (@ESCOLARIDADE = @CD_ESCOLARIDADE))
			BEGIN
				IF((@SALARIO >= @MENOR_VALOR) AND (@SALARIO <= @MAIOR_VALOR))
					BEGIN
						SET @RETORNO = 1
					END
			END
		FETCH C_SALARIO INTO @CD_CARGO, @CD_ESCOLARIDADE, @MENOR_VALOR, @MAIOR_VALOR
	END

SELECT @RETORNO

CLOSE C_SALARIO
DEALLOCATE C_SALARIO