CREATE PROCEDURE SP_CLASSIFICA_CLIENTE (@DATAINCLUSAO DATETIME, @QUANTIDADEPRODUTOS INT, @RETORNO BIT OUTPUT) AS

SET @RETORNO = 0

IF ((@DATAINCLUSAO >= '01/03/2010') OR (@QUANTIDADEPRODUTOS > 50))
BEGIN
	SET @RETORNO = 1
END

--------------------------------------------------------

CREATE PROCEDURE SP_COPIA_CLENTE AS

DECLARE @CD_CLIENTE INT
DECLARE @NM_CLIENTE VARCHAR(60)
DECLARE @CPF INT
DECLARE @DT_INCLUSAO DATETIME

DECLARE @QUANTIDADEPRODUTOS INT
DECLARE @RETORNO BIT

DECLARE C_CLIENTE CURSOR FOR
	SELECT C.CD_CLIENTE, C.NM_CLIENTE, C.CPF, C.DT_INCLUSAO FROM TB_CLIENTE C
	
OPEN C_CLIENTE
FETCH C_CLIENTE INTO @CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_INCLUSAO

WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @QUANTIDADEPRODUTOS = (SELECT V.QUANTIDADE FROM TB_CLIENTE C
											INNER JOIN TB_VENDAS V
											ON (C.CD_CLIENTE = V.CD_CLIENTE)
											GROUP BY V.QUANTIDADE, C.CD_CLIENTE
											HAVING (C.CD_CLIENTE) = @CD_CLIENTE)
		EXEC SP_CLASSIFICA_CLIENTE @DT_INCLUSAO, @QUANTIDADEPRODUTOS, @RETORNO OUTPUT
		
		IF(@RETORNO = 1)
			BEGIN
				INSERT INTO TB_CLIENTE_PARCEIRO VALUES(@CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_INCLUSAO)
			END
		ELSE
			BEGIN
				INSERT INTO TB_CLIENTE_ALVO VALUES(@CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_INCLUSAO)
			END
		
		FETCH C_CLIENTE INTO @CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_INCLUSAO
	END

CLOSE C_CLIENTE
DEALLOCATE C_CLIENTE
