CREATE PROCEDURE SP_FAIXA_SALARIAL_FUNCIONARIO() AS

DECLARE @MATRICULA INT
DECLARE @NOME VARCHAR(50)
DECLARE @CD_CARGO INT
DECLARE @CD_ESCOLARIDADE INT
DECLARE @SALARIO NUMERIC(10,2)
DECLARE @RETORNO BIT

SET @RETORNO = 0

DECLARE C_SALARIO_F CURSOR FOR 
	SELECT F.MATRICULA, F.NOME, F.CD_CARGO, F.CD_ESCOLARIDADE, F.SALARIO FROM TB_FUNCIONARIO F

OPEN C_SALARIO_F
FETCH C_SALARIO_F INTO @MATRICULA, @NOME, @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		EXEC SP_FAIXA_SALARIAL @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO, @RETORNO OUTPUT
		IF(@RETORNO = TRUE)
			BEGIN
				SELECT 'ENTROU'
			END
		FETCH C_SALARIO_F INTO @MATRICULA, @NOME, @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO
	END

CLOSE C_SALARIO_F
DEALLOCATE C_SALARIO_F

CREATE PROCEDURE SP_FAIXA_SALARIAL_FUNCIONARIO AS

DECLARE @MATRICULA INT
DECLARE @NOME VARCHAR(50)
DECLARE @CD_CARGO INT
DECLARE @CD_ESCOLARIDADE INT
DECLARE @SALARIO NUMERIC(10,2)
DECLARE @RETORNO BIT

SET @RETORNO = 0

DECLARE C_SALARIO_F CURSOR FOR 
	SELECT F.MATRICULA, F.NOME, F.CD_CARGO, F.CD_ESCOLARIDADE, F.SALARIO FROM TB_FUNCIONARIO F

OPEN C_SALARIO_F
FETCH C_SALARIO_F INTO @MATRICULA, @NOME, @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		EXEC SP_FAIXA_SALARIAL @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO, @RETORNO OUTPUT
		IF(@RETORNO = 0)
			BEGIN
				INSERT INTO TB_LOG_FUNCIONARIO (MATRICULA, ERRO, DATA_ERRO) VALUES (@MATRICULA, 'SALARIO INVALIDO', '22/04/2015 14:02:36')
			END
		FETCH C_SALARIO_F INTO @MATRICULA, @NOME, @CD_CARGO, @CD_ESCOLARIDADE, @SALARIO
	END

CLOSE C_SALARIO_F
DEALLOCATE C_SALARIO_F