CREATE PROCEDURE SP_OBTEM_RESUMO(@CD_USUARIO INT, @MES INT, @ANO INT, @TOTALRECEITA NUMERIC(10,2) OUTPUT, @TOTALDESPESA NUMERIC(10,2) OUTPUT) AS

SET @TOTALRECEITA = (SELECT SUM(L.VALOR) FROM TB_LANCAMENTOS L
							WHERE ((L.TP_LANCAMENTO = 'R') AND (L.CD_USUARIO = @CD_USUARIO)
										AND (L.MES = @MES) AND (L.ANO = @ANO)) 
							GROUP BY L.CD_USUARIO)

SET @TOTALDESPESA = (SELECT SUM(L.VALOR) FROM TB_LANCAMENTOS L
							WHERE ((L.TP_LANCAMENTO = 'D') AND (L.CD_USUARIO = @CD_USUARIO)
										AND (L.MES = @MES) AND (L.ANO = @ANO)) 
							GROUP BY L.CD_USUARIO)
------------------------------------------------

CREATE PROCEDURE SP_INCLUI_RESUMO_FINANCEIRO(@ANO INT) AS

DECLARE @CD_USUARIO INT

DECLARE @MES INT
SET @MES = 1

DECLARE @TOTALRECEITA NUMERIC(10,2)
DECLARE @TOTALDESPESA NUMERIC(10,2)
SET @TOTALRECEITA = 0
SET @TOTALDESPESA = 0

DECLARE C_USUARIO CURSOR FOR 
	SELECT U.CD_USUARIO FROM TB_USUARIO U

OPEN C_USUARIO
FETCH C_USUARIO INTO @CD_USUARIO
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		WHILE(@MES < 13)
			BEGIN
				EXEC SP_OBTEM_RESUMO @CD_USUARIO, @MES, @ANO, @TOTALRECEITA OUTPUT, @TOTALDESPESA OUTPUT
				IF((@TOTALDESPESA IS NOT NULL) AND (@TOTALRECEITA IS NULL))
					BEGIN
						INSERT INTO TB_RESUMO_FINANCEIRO VALUES (@CD_USUARIO, @MES, @ANO, 0, @TOTALDESPESA)
					END
				ELSE
				IF((@TOTALDESPESA IS NULL) AND (@TOTALRECEITA IS NOT NULL))
					BEGIN
						INSERT INTO TB_RESUMO_FINANCEIRO VALUES (@CD_USUARIO, @MES, @ANO, @TOTALRECEITA, 0)
					END
				ELSE
				IF((@TOTALDESPESA IS NOT NULL) AND (@TOTALRECEITA IS NOT NULL))
					BEGIN
						INSERT INTO TB_RESUMO_FINANCEIRO VALUES (@CD_USUARIO, @MES, @ANO, @TOTALRECEITA, @TOTALDESPESA)
					END
				ELSE
					BEGIN
						INSERT INTO TB_RESUMO_FINANCEIRO VALUES (@CD_USUARIO, @MES, @ANO, 0, 0)
					END
				SET @MES += 1
			END
			SET @MES = 1
		FETCH C_USUARIO INTO @CD_USUARIO
	END
CLOSE C_USUARIO
DEALLOCATE C_USUARIO