CREATE PROCEDURE SP_CLASSIFICA_CLIENTE(@QUANTIDADECONTAS INT, @SALDOTOTAL NUMERIC(10,2), @RETORNO BIT OUTPUT) AS

IF(@SALDOTOTAL >= 1000)
	BEGIN
		SELECT 'VIP'
	END
ELSE
	IF((@SALDOTOTAL >= 5000) AND (@SALDOTOTAL < 10000) AND (@QUANTIDADECONTAS > 2))
		BEGIN
			SELECT 'VIP'
		END
	ELSE
		SELECT 'NORMAL'
---------------------------------------------------
ALTER PROCEDURE SP_CLASSIFICA_CLIENTE(@QUANTIDADECONTAS INT, @SALDOTOTAL NUMERIC(10,2), @RETORNO BIT OUTPUT) AS

SET @RETORNO = 0

IF(@SALDOTOTAL >= 10000)
	BEGIN
		SET @RETORNO = 1
	END
ELSE
	IF((@SALDOTOTAL >= 5000) AND (@SALDOTOTAL < 10000) AND (@QUANTIDADECONTAS > 2))
		BEGIN
			SET @RETORNO = 1
		END
-------------------------------------------------

CREATE PROCEDURE SP_ATUALIZA_TIPO_CLIENTE AS

DECLARE @CD_CLIENTE INT 
DECLARE @NM_CLIENTE VARCHAR(60)
DECLARE @CPF INT
DECLARE @DT_NASCIMENTO DATETIME
DECLARE @TIPO_CLIENTE VARCHAR(40)
DECLARE @RETORNO BIT

DECLARE @QUANTIDADECONTAS INT
DECLARE @SALDOTOTAL NUMERIC(10,2)
DECLARE C_CLIENTE CURSOR FOR 
	SELECT C.CD_CLIENTE, C.NM_CLIENTE, C.CPF, C.DT_NASCIMENTO, C.TIPO_CLIENTE FROM TB_CLIENTE C

OPEN C_CLIENTE
FETCH C_CLIENTE INTO @CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_NASCIMENTO, @TIPO_CLIENTE
		
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		SET @QUANTIDADECONTAS = (SELECT COUNT(CO.NR_CONTA) FROM TB_CLIENTE C
		INNER JOIN TB_CONTA CO
		ON (CO.CD_CLIENTE = C.CD_CLIENTE)
		GROUP BY C.CD_CLIENTE
		HAVING (C.CD_CLIENTE) = @CD_CLIENTE)
		
		SET @SALDOTOTAL = (SELECT SUM(CO.SALDO) FROM TB_CLIENTE C
		INNER JOIN TB_CONTA CO
		ON (CO.CD_CLIENTE = C.CD_CLIENTE)
		GROUP BY C.CD_CLIENTE
		HAVING C.CD_CLIENTE = @CD_CLIENTE)
		
		EXEC SP_CLASSIFICA_CLIENTE @QUANTIDADECONTAS, @SALDOTOTAL, @RETORNO OUTPUT
		
		IF(@RETORNO = 1)
			BEGIN
				UPDATE TB_CLIENTE SET TIPO_CLIENTE = 'VIP' WHERE (@CD_CLIENTE = CD_CLIENTE)
			END
		ELSE
			BEGIN
				UPDATE TB_CLIENTE SET TIPO_CLIENTE = 'NORMAL' WHERE (@CD_CLIENTE = CD_CLIENTE)
			END

		FETCH C_CLIENTE INTO @CD_CLIENTE, @NM_CLIENTE, @CPF, @DT_NASCIMENTO, @TIPO_CLIENTE
	END

CLOSE C_CLIENTE
DEALLOCATE C_CLIENTE