CREATE DATABASE AULA_07
USE AULA_07


SELECT * FROM TB_PRODUTO

ALTER PROCEDURE SP_INCLUIR_PRODUTO_AUXILIO AS
BEGIN
	DECLARE @COD_PRODUTO INT, @DESCRICAO VARCHAR(50), @COD_EMBALAGEM CHAR(10), @CAMPO_FINAL VARCHAR(4), @COMPRIMENTO SMALLINT
	DECLARE C_INCLUIR_DADOS CURSOR FOR
	SELECT COD_PRODUTO,DESCRICAO,COD_EMBALAGEM FROM TB_PRODUTO

	OPEN C_INCLUIR_DADOS 
	FETCH C_INCLUIR_DADOS INTO @COD_PRODUTO,@DESCRICAO,@COD_EMBALAGEM
	wHILE(@@FETCH_STATUS = 0)
		BEGIN
		-- CHAR(9) USEI REPLACE PARA REMOVER A TABULAÇÃO
		SET @CAMPO_FINAL = (SELECT(LTRIM(RTRIM(REPLACE(@COD_EMBALAGEM, CHAR(9),'')))))
		--CONCATENAR A STRING
		SET @COMPRIMENTO = LEN(@CAMPO_FINAL)
		SET @CAMPO_FINAL  = REPLICATE('0',4-@COMPRIMENTO)+@CAMPO_FINAL
			
				INSERT INTO TB_PRODUTO_AUX VALUES(@COD_PRODUTO,@DESCRICAO,@CAMPO_FINAL)
				FETCH C_INCLUIR_DADOS INTO @COD_PRODUTO,@DESCRICAO,@COD_EMBALAGEM
		END
	CLOSE C_INCLUIR_DADOS
	DEALLOCATE C_INCLUIR_DADOS
END
DELETE TB_PRODUTO_AUX
EXEC SP_INCLUIR_PRODUTO_AUXILIO

select * from tb_produto
SELECT * FROM TB_PRODUTO_AUX

SELECT * FROM TB_PRODUTO