CREATE TABLE TB_PRODUTO (
  COD_PRODUTO INT NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR(50) NOT NULL,
  COD_EMBALAGEM CHAR(10) NULL
)  

CREATE TABLE TB_PRODUTO_AUX (
  COD_PRODUTO INT NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR(50) NOT NULL,
  COD_EMBALAGEM VARCHAR(4) NULL
)

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (1, 'ARROZ','	4')

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (2, 'FEIJAO','   8')

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (3, 'CRAVO', '94	    ')

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (4, 'REFRIGERANTE', '75T	')

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (5, 'PEIXE', '	6R')

INSERT INTO TB_PRODUTO (COD_PRODUTO, DESCRICAO, COD_EMBALAGEM)
VALUES (6, 'CARNE', '875   ')

    





