DROP TABLE TB_OFERECE_PACOTE_CLIENTE
DROP TABLE TB_PACOTE_SAIDA
DROP TABLE TB_PACOTE
DROP TABLE TB_INTERESSE_CLIENTE
DROP TABLE TB_DESTINO
DROP TABLE TB_CLIENTE

CREATE TABLE TB_CLIENTE (
   COD_CLIENTE		INT NOT NULL PRIMARY KEY,
   NM_CLIENTE		VARCHAR(50) NOT NULL,
   CPF				VARCHAR(13) NULL,
   ENDERECO			VARCHAR(100) NULL,
   TELEFONE			VARCHAR(20) NULL,
   TELEFONE_CELULAR VARCHAR(20) NULL,
   EMAIL			VARCHAR(100) NULL
)

CREATE TABLE TB_DESTINO (
   COD_DESTINO		INT NOT NULL PRIMARY KEY,
   DESCRICAO		VARCHAR(100) NOT NULL,
   ESTADO			CHAR(2) NOT NULL
)

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (1, 'BARRA DE SÃO MIGUEL', 'AL')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (2, 'PORTO DE GALINHAS','PE')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (3, 'PORTO SEGURO','BA')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (4, 'SALVADOR','BA')

CREATE TABLE TB_INTERESSE_CLIENTE (
   ID_INTERESSE_CLIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   COD_DESTINO			INT NOT NULL REFERENCES TB_DESTINO,
   COD_CLIENTE			INT NOT NULL REFERENCES TB_CLIENTE,
   DATA_INICIAL			DATETIME NOT NULL,
   DATA_FINAL			DATETIME NOT NULL
)

CREATE TABLE TB_PACOTE (
    COD_PACOTE		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    DESCRICAO		VARCHAR(200) NOT NULL,
    COD_DESTINO		INT NOT NULL REFERENCES TB_DESTINO,
    NR_DIAS		INT,
    DATA_INICIAL    DATETIME NOT NULL,
    DATA_FINAL      DATETIME NOT NULL,
    VALIDO          CHAR(3) CHECK (VALIDO IN ('SIM','NAO'))
)     

CREATE TABLE TB_PACOTE_SAIDA (
    ID_PACOTE_SAIDA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    COD_PACOTE		INT NOT NULL REFERENCES TB_PACOTE,
    DATA_SAIDA		DATETIME NOT NULL,
    UNIQUE (COD_PACOTE, DATA_SAIDA)
)    
    

CREATE TABLE TB_OFERECE_PACOTE_CLIENTE (
    CD_OFERECE	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    COD_CLIENTE INT NOT NULL REFERENCES TB_CLIENTE,
    COD_PACOTE	INT NOT NULL REFERENCES TB_PACOTE,
    OFERECIDO	CHAR(3) CHECK (OFERECIDO IN ('SIM','NAO'))
)



    

   