-------------------------------------------------------------
-- INSERT PACOTE 
------------------------------------------------------------
SELECT * FROM TB_CLIENTE

SELECT * FROM TB_DESTINO

SELECT * FROM TB_INTERESSE_CLIENTE

SELECT * FROM TB_OFERECE_PACOTE_CLIENTE

SELECT * FROM TB_PACOTE

SELECT * FROM TB_PACOTE_SAIDA

-------------------------------------------------------------
-- INSERT CLIENTE
------------------------------------------------------------

INSERT INTO TB_CLIENTE (COD_CLIENTE,NM_CLIENTE,CPF,ENDERECO)VALUES 
(10,'ALAN','12345678909','AVENIDA CAPTULINO ALVES DOS SANTOS'),
(20,'BRENDEL SANTOS','12341231209','RUA MANOEL ANTONIO DE OLIVEIRA'),
(30,'IURY BATISTA','11231311119','RUA 24 JUNHO'),
(40,'EDSON LIMA','11111238909','AVENIDA ZEFINHA DE CAPTULINO'),
(50,'LETICIA SOUZA','00098887909','AVENIDA CAPTULINO ALVES DOS SANTOS')
-------------------------------------------------------------
-- INSERT CLIENTE
------------------------------------------------------------
DELETE TB_PACOTE
DBCC CHECKIDENT(TB_PACOTE, RESEED, 0)
TRUNCATE TABLE TB_PACOTE_SAIDA
INSERT INTO TB_PACOTE (DESCRICAO,COD_DESTINO,NR_DIAS,DATA_INICIAL,DATA_FINAL,VALIDO) VALUES
('VIAGEM',1,5,'20120101','20120115','SIM')

INSERT INTO TB_PACOTE (DESCRICAO,COD_DESTINO,DATA_INICIAL,DATA_FINAL) VALUES
('VIAGEM',1,'20120101','20120115')
DELETE TB_PACOTE_SAIDA
DBCC CHECKIDENT(TB_PACOTE_SAIDA, RESEED, 1)
DBCC CHECKIDENT(TB_PACOTE, RESEED, 0)
UPDATE TB_PACOTE SET NR_DIAS = 1 WHERE COD_PACOTE = 1
UPDATE TB_PACOTE SET VALIDO = 'SIM' WHERE COD_PACOTE = 1
SELECT * FROM TB_PACOTE_SAIDA
SELECT * FROM TB_PACOTE


SELECT * FROM TB_INTERESSE_CLIENTE

TRUNCATE TABLE TB_INTERESSE_CLIENTE

SELECT * FROM TB_PACOTE_SAIDA
SELECT * FROM TB_DESTINO
SELECT * FROM TB_PACOTE
SELECT * FROM TB_OFERECE_PACOTE_CLIENTE
INSERT INTO TB_INTERESSE_CLIENTE VALUES
(1,10,'20120101','20120114'),
(2,20,'20120101','20120123'),
(3,30,'20120101','20120115')


SELECT * FROM TB_INTERESSE_CLIENTE
SELECT * FROM TB_CLIENTE

EXEC SP_OFERECER
TRUNCATE TABLE TB_OFERECE_PACOTE_CLIENTE
SELECT * FROM TB_OFERECE_PACOTE_CLIENTE