ALTER TRIGGER TG_CPF ON TB_FUNCIONARIO_CPF
AFTER INSERT
AS
	BEGIN
		IF EXISTS (SELECT COUNT(CPF) FROM TB_FUNCIONARIO_CPF GROUP BY CPF HAVING COUNT(CPF) > 1)
			BEGIN
				ROLLBACK TRANSACTION
		END																				
	END