ALTER TRIGGER [dbo].[TG_VENDAS_HORARIO] ON [dbo].[TB_VENDAS]
AFTER INSERT
AS

	IF EXISTS (SELECT I.DT_VENDA, I.CD_PRODUTO, I.QUANTIDADE, I.VALOR  FROM INSERTED I
		WHERE (((DATEPART(HOUR, I.DT_VENDA) >= 18) AND (DATEPART(HOUR, I.DT_VENDA) < 22)) OR
					((DATEPART(HOUR, I.DT_VENDA) >= 12) AND (DATEPART(HOUR, I.DT_VENDA) < 14))))
			BEGIN
				ROLLBACK TRANSACTION
			END
