CREATE TRIGGER [dbo].[TG_VENDAS_LOG] ON [dbo].[TB_VENDAS]
AFTER INSERT
AS
	INSERT INTO TB_LOG_VENDAS (DT_LOG, TIPO_OPERACAO, CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE_NOVA, VALOR_NOVO)
	SELECT GETDATE(), 'I', CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE, VALOR FROM INSERTED I