ALTER TRIGGER TG_CPF ON TB_FUNCIONARIO_CPF
AFTER INSERT
AS
	BEGIN
		DECLARE @CPF VARCHAR(50)
					
		DECLARE C_FUNCIONARIO_CPF CURSOR FOR 
			SELECT TF.CPF FROM INSERTED TF
	
		OPEN C_FUNCIONARIO_CPF
		FETCH C_FUNCIONARIO_CPF INTO @CPF
				
		WHILE(@@FETCH_STATUS = 0)
			BEGIN
				BEGIN TRANSACTION
				IF EXISTS (SELECT CPF, COUNT(*) FROM TB_FUNCIONARIO_CPF WHERE CPF = @CPF GROUP BY CPF HAVING COUNT(*) > 1)
					BEGIN
						ROLLBACK TRANSACTION
					END																				
				FETCH C_FUNCIONARIO_CPF INTO @CPF
			END
		
		CLOSE C_FUNCIONARIO_CPF
		DEALLOCATE C_FUNCIONARIO_CPF
	END