ALTER TRIGGER TG_ALUNO_INSERT
ON TB_ALUNO
AFTER INSERT, UPDATE
AS
	DELETE FROM TB_LOG_PENDENCIAS WHERE MATRICULA IN(
		SELECT MATRICULA FROM INSERTED	
	) 
		INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA)
		SELECT MATRICULA, NOME, 'FALTA RG' FROM INSERTED
		WHERE(RG IS NULL)
	
		INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA)
		SELECT MATRICULA, NOME, 'FALTA ENDERECO' FROM INSERTED
		WHERE(ENDERECO IS NULL)
	
		INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA)
		SELECT MATRICULA, NOME, 'FALTA TELEFONE' FROM INSERTED
		WHERE(TELEFONE IS NULL)
