ALTER TRIGGER TG_FAIXA_SALARIAL ON TB_FUNCIONARIO_SALARIO
AFTER UPDATE
AS

	IF EXISTS (SELECT I.MATRICULA, I.NOME, GETDATE(), (D.SALARIO + D.GRATIFICACAO), (I.SALARIO + I.GRATIFICACAO)  FROM INSERTED I
	INNER JOIN DELETED D
	ON (I.MATRICULA = D.MATRICULA)
	WHERE (I.SALARIO + I.GRATIFICACAO) > ((0.30 * (D.SALARIO + D.GRATIFICACAO)) + (D.SALARIO + D.GRATIFICACAO)))
		BEGIN
			ROLLBACK TRANSACTION
		END