ALTER TRIGGER [dbo].[TG_VENDAS_LOG_DELETE] ON [dbo].[TB_VENDAS]
AFTER DELETE
AS
	INSERT INTO TB_LOG_VENDAS (DT_LOG, TIPO_OPERACAO, CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE_ANTIGA, VALOR_ANTIGO)
	SELECT GETDATE(), 'R', CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE, VALOR FROM DELETED 