ALTER dbo.TB_ALUNOTRIGGER TG_ALUNO_UPDATE
ON TB_ALUNO
AFTER UPDATE
AS
	DELETE FROM TB_LOG_PENDENCIAS WHERE PENDENCIA = 'FALTA RG' AND MATRICULA IN(
		SELECT MATRICULA FROM INSERTED
		
	) 
	DELETE FROM TB_LOG_PENDENCIAS WHERE PENDENCIA = 'FALTA ENDERECO' AND MATRICULA IN(
		SELECT MATRICULA FROM INSERTED
		
	) 
	DELETE FROM TB_LOG_PENDENCIAS WHERE PENDENCIA = 'FALTA TELEFONE' AND MATRICULA IN(
		SELECT MATRICULA FROM INSERTED
		
	) 