ALTER TRIGGER [dbo].[TG_SALARIO_FUNCIONARIO] ON [dbo].[TB_FUNCIONARIO_SALARIO]
AFTER UPDATE
AS
	INSERT INTO TB_LOG_AUMENTO_FUNCIONARIO (MATRICULA, NOME, DATA, SALARIO_INTEGRAL_ANTIGO, SALARIO_INTEGRAL_NOVO)
	SELECT I.MATRICULA, I.NOME, GETDATE(), (D.SALARIO + D.GRATIFICACAO), (I.SALARIO + I.GRATIFICACAO)  FROM INSERTED I
	INNER JOIN DELETED D
	ON (I.MATRICULA = D.MATRICULA)
	WHERE (I.SALARIO + I.GRATIFICACAO) > (D.SALARIO + D.GRATIFICACAO)
		