/*
Criar uma função SF_TO_CHAR para transformar uma data em uma cadeia de caracteres. 
A função deve receber como parâmetros uma data e uma máscara.  
Exemplos de utilização e de máscaras possíveis:  

select dbo.sf_TO_CHAR(GETDATE(),'DD/MM/YYYY') >03/04/2011 
select dbo.sf_TO_CHAR(GETDATE(),'DD-MM-YYYY') >03-04-2011 
select dbo.sf_TO_CHAR(GETDATE(),'DD.MM.YYYY') >03.04.2011 
select dbo.sf_TO_CHAR(GETDATE(),'DD/MM/YYYY HH:MI:SS') >03/04/2011 21:25:34 
select dbo.sf_TO_CHAR(GETDATE(),'DD/MM/YYYY às HH:MI') >03/04/2011 às 21:27 
select dbo.sf_TO_CHAR(GETDATE(),'HH:MI') >21:28 
select dbo.sf_TO_CHAR(GETDATE(),'YYYYMMDD') >20110403 
select dbo.sf_TO_CHAR(GETDATE(),'DD de Month de YYYY') >03 de Abril de 2011 
select dbo.sf_TO_CHAR(GETDATE(),'DD de Month, YYYY.') >03 de Abril, 2011.   

*/
PRINT SUBSTRING('YYYY/MM/DD',5,(LEN('YYYY/MM/DD')-4))
PRINT  LEN('YYYY/MM/DD')

DECLARE @DATA DATETIME, @DATA_ATUAL VARCHAR(45)
SET @DATA = GETDATE()
EXEC @DATA_ATUAL =  SF_TO_CHAR '20120101','Month'

PRINT @DATA_ATUAL

ALTER FUNCTION SF_TO_CHAR(@DATA DATETIME,@MASCARA VARCHAR(45) )
RETURNS VARCHAR(45)
AS
BEGIN
DECLARE @DATA_RETURN DATETIME, @DATA_MANIPULADA VARCHAR(50), 
@DIA VARCHAR(10),@MES VARCHAR(10),@NMMES VARCHAR(10), @ANOYY VARCHAR(10),@ANOYYYY VARCHAR(10),@P_MASCARA VARCHAR(5),@S_MASCARA VARCHAR(5),
@HORA VARCHAR(10),@MINUTO VARCHAR(10), @SEGUNDO VARCHAR(10)

SET @DIA = DATEPART(DD,@DATA)
SET @MES = DATEPART(MM,@DATA)
SET @NMMES = DATENAME(MM,@DATA)
SET @ANOYY = DATEPART(YY,@DATA)
SET @ANOYYYY = DATEPART(YYYY,@DATA)
SET @HORA = DATEPART(HH,@DATA)
SET @MINUTO = DATEPART(MI,@DATA)
SET @SEGUNDO = DATEPART(SS,@DATA)
	
SET @DATA_MANIPULADA = @MASCARA

SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'DD', (SELECT dbo.SF_LPAD (@DIA,2,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'MM',(SELECT dbo.SF_LPAD (@MES,2,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'Month',@NMMES)
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'YY',(SELECT dbo.SF_LPAD (@ANOYY,2,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'YYYY',(SELECT dbo.SF_LPAD (@ANOYYYY,4,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'HH',(SELECT dbo.SF_LPAD (@HORA,2,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'MI',(SELECT dbo.SF_LPAD (@MINUTO,2,'0')))
SET @DATA_MANIPULADA = REPLACE(@DATA_MANIPULADA,'SS',(SELECT dbo.SF_LPAD (@SEGUNDO,2,'0')))
RETURN @DATA_MANIPULADA
END