
-- TRIGGER PARA MUDAR O STATUS DO QUARTO QUANDO REALIZA UMA HOSPEDAGEM
CREATE TRIGGER TG_ATUALIZA_STATUS_QUARTO
ON HOSPEDAGEM
AFTER INSERT 
AS
   DECLARE @IDQUARTO INT
   SELECT @IDQUARTO =  (SELECT IDQUARTO FROM INSERTED)
   UPDATE QUARTO SET STATUS = 'O' WHERE IDQUARTO = @IDQUARTO

GO
-- MUDA O STATUS DO QUARTO QUANDO FINALIZA  AHOSPEDAGEM
CREATE TRIGGER TG_ATUALIZA_STATUS_QUARTO_LIVRE
ON HOSPEDAGEM
AFTER UPDATE
AS
   DECLARE @ABERTO BIT, @DATALIBERACAO DATETIME, @IDQUARTO INT
   SELECT @ABERTO =  (SELECT ABERTO FROM DELETED)
   SELECT @DATALIBERACAO = (SELECT DATALIBERACAO FROM DELETED)
   SELECT @IDQUARTO = (SELECT IDQUARTO FROM DELETED)

   IF(@ABERTO = 0 AND @DATALIBERACAO IS NOT NULL )
	   BEGIN
	   UPDATE QUARTO SET STATUS = 'L' WHERE IDQUARTO = @IDQUARTO

	   END
   GO
-- TRIGGER PARA MUDAR A QUANTODADE DE PRODUTO QUANDO ADICIONA UM ITEM
CREATE TRIGGER TG_ATUALIZA_QUANTIDADE_PRODUTO
ON ITEM
AFTER INSERT 
AS
   DECLARE @QUANTIDADE INT, @IDPRODUTO INT,@MENSAGEM_ERRO varchar(45)
   SELECT @QUANTIDADE =  (SELECT QUANTIDADE FROM INSERTED)
   SELECT @IDPRODUTO = (SELECT IDPRODUTO FROM INSERTED)

   IF((SELECT QUANTIDADE FROM PRODUTO WHERE IDPRODUTO = @IDPRODUTO) >= @QUANTIDADE)
		   BEGIN
				UPDATE PRODUTO SET QUANTIDADE = QUANTIDADE - @QUANTIDADE WHERE IDPRODUTO = @IDPRODUTO
		   END
	ELSE
		BEGIN
			SET @MENSAGEM_ERRO = 'QUANTIDADE MAIOR DO QUE O NORMAL';
			RAISERROR (@MENSAGEM_ERRO, 1, 1)
			ROLLBACK
		END
   
GO
CREATE TRIGGER TG_ATUALIZA_VALOR_PACOTE_HOSPEDAGEM
ON HOSPEDAGEM
AFTER INSERT, update
AS
	DECLARE @IDPACOTEHOSPEDAGEM INT, @VALORHOSPEDAGEM NUMERIC(10,2)
	SELECT @IDPACOTEHOSPEDAGEM  = (SELECT IDPACOTEHOSPEDAGEM FROM INSERTED)
	SELECT @VALORHOSPEDAGEM = (select sum(valorhospedagem) from hospedagem where idPacotehospedagem = @idpacotehospedagem )
	UPDATE pacotehospedagem set valorTotal = 0 ,subTotal = 0 where idPacoteHospedagem = @IDPACOTEHOSPEDAGEM
	UPDATE pacotehospedagem set valorTotal = valorTotal + @VALORHOSPEDAGEM,subTotal = subTotal + @VALORHOSPEDAGEM where idPacoteHospedagem = @IDPACOTEHOSPEDAGEM
GO
CREATE TRIGGER TG_ATUALIZA_VALOR_HOSPEDAGEM
ON item
after insert, update
as 
	DECLARE @IDhospedagem INT, @VALORtotal NUMERIC(10,2)
	SELECT @IDHOSPEDAGEM  = (SELECT IDHOSPEDAGEM FROM INSERTED)
	SELECT @VALORtotal = (select sum(valortotal) from item where idhospedagem = @idhospedagem )
	UPDATE Hospedagem set valorHospedagem = 0  where idHospedagem = @IDHOSPEDAGEM
	UPDATE Hospedagem set valorHospedagem = valorHospedagem + @VALORtotal where idHospedagem = @IDHOSPEDAGEM




