CREATE DATABASE AULA_06
USE AULA_06

/*
Criar uma tabela TB_VENDAS com os seguintes atributos: CD_VENDA, DT_VENDA, MATRICULA, CD_PRODUTO, QUANTIDADE.
*/
-- CIA플O DE TABELAS 

CREATE TABLE TB_VENDAS(
CD_VENDA INT NOT NULL IDENTITY(1,1),
DT_VENDA DATETIME NOT NULL,
MATRICULA INT NOT NULL,
CD_PRODUTO INT NOT NULL,
QUANTIDADE NUMERIC(10,2) NOT NULL
)

ALTER TABLE TB_VENDAS ADD CONSTRAINT PK_TB_VENDAS PRIMARY KEY(CD_VENDA)

/*
Criar uma tabela TB_VENDAS_MENSAL com os seguintes atributos: 
MATRICULA, ANO, MES, QUANTIDADE_MES_ATUAL, QUANTIDADE_MES_ANTERIOR, VARIACAO.
*/


CREATE TABLE TB_VENDAS_MENSAL (
MATRICULA INT NOT NULL,
ANO INT NOT NULL,
MES INT NOT NULL,
QUANTIDADE_MES_ATUAL NUMERIC(10,2) NULL,
QUANTIDADE_MES_ANTERIOR NUMERIC(10,2) NULL,
VARIA플O NUMERIC(10,2) NOT NULL
)

DROP TABLE TB_VENDAS_MENSAL
-- FIM DA CRIA플O DAS TABELAS
-- INICIO DA INSER플O DE DADOS
/*
CD_VENDA DT_VENDA MATRICULA CD_PRODUTO QUANTIDADE
----------- ------------ ----------- ----------- ------------
1 2009-01-01 10 1001 50.00
2 2009-01-01 10 1002 50.00
3 2009-02-01 10 1001 150.00

4 2009-01-01 30 1001 200.00
5 2009-01-01 30 1001 100.00
6 2009-02-01 30 1001 150.00

7 2009-05-01 40 1002 100.00
8 2009-05-10 40 1002 200.00
9 2009-07-05 40 1001 250.00
*/
SELECT * FROM TB_VENDAS
INSERT INTO TB_VENDAS(DT_VENDA,MATRICULA,CD_PRODUTO,QUANTIDADE) VALUES
('20090101',10,1001,50),
('20090101',10,1002,50),
('20090201',10,1001,150),

('20090101',30,1001,200),
('20090101',30,1001,100),
('20090201',30,1001,150),

('20090501',40,1002,100),
('20090510',40,1002,200),
('20090705',40,1001,250)

-- FIM DA INSER플O DE DADOS NA TABELA DE VENDAS




CREATE PROCEDURE  SP_EXISTE (@MATRICULA INT ,@ANO INT, @MES INT, @EXIST VARCHAR(10) OUTPUT) AS
	SET @EXIST = (SELECT ANO FROM TB_VENDAS_MENSAL WHERE (MATRICULA = @MATRICULA AND (ANO = @ANO AND MES = @MES)))
		




ALTER PROCEDURE SP_INERIR_VENDAS AS
	BEGIN
		DECLARE @MATRICULA INT, @DATA_VENDA DATETIME, @QUANTIDADE NUMERIC(10,2)

		DECLARE C_INSERT CURSOR FOR
		SELECT DISTINCT DT_VENDA AS DATA, MATRICULA,QUANTIDADE FROM TB_VENDAS

		OPEN C_INSERT 
		FETCH C_INSERT INTO @DATA_VENDA,@MATRICULA,@QUANTIDADE

		WHILE(@@FETCH_STATUS = 0)
			BEGIN
			
				
			
				DECLARE @VARIACAO decimal(10,2),@QUANTIDADE_MES_ATUAL NUMERIC(10,2), @QUANTIDADE_MES_ANTERIOR INT,@MES_ANTERIOR DATETIME, @EXIST VARCHAR(10), @ANO INT , @MES INT
	
				
				SET @ANO = CAST( YEAR(@DATA_VENDA) AS INT)
				SET @MES = CAST(MONTH(@DATA_VENDA) AS INT)

			EXEC SP_EXISTE @MATRICULA,@ANO,@MES,@EXIST OUTPUT

			IF(@EXIST IS NULL)
				BEGIN
			
				SET @MES_ANTERIOR = DATEADD(MONTH,-1, @DATA_VENDA)
			
				
				SET @QUANTIDADE_MES_ATUAL = (SELECT SUM(QUANTIDADE)
													FROM 
														TB_VENDAS 
													WHERE 
														( MONTH(DT_VENDA )= MONTH( @DATA_VENDA ) AND YEAR( DT_VENDA) = YEAR( @DATA_VENDA ) AND MATRICULA = @MATRICULA ) )

				SET @QUANTIDADE_MES_ANTERIOR = (SELECT SUM(QUANTIDADE) 
													FROM 
														TB_VENDAS 
													WHERE 
														(MONTH(DT_VENDA )=MONTH(@MES_ANTERIOR) AND YEAR(DT_VENDA )=YEAR(@MES_ANTERIOR)  AND MATRICULA = @MATRICULA ) )
					IF(@QUANTIDADE_MES_ANTERIOR > 0)
						BEGIN
							SELECT @VARIACAO = ((@QUANTIDADE_MES_ATUAL - @QUANTIDADE_MES_ANTERIOR) / @QUANTIDADE_MES_ANTERIOR)
						END
					ELSE
						BEGIN
							SET @VARIACAO	= 0.0
							SET @QUANTIDADE_MES_ANTERIOR = 0
			
						END

			
						INSERT INTO TB_VENDAS_MENSAL VALUES
							(@MATRICULA,@ANO,@MES,@QUANTIDADE_MES_ATUAL,@QUANTIDADE_MES_ANTERIOR,@VARIACAO)
					END
				FETCH C_INSERT INTO @DATA_VENDA,@MATRICULA,@QUANTIDADE
			END
		CLOSE C_INSERT
		DEALLOCATE C_INSERT
	END
	
EXEC SP_INERIR_VENDAS

SELECT * FROM TB_VENDAS_MENSAL ORDER BY MATRICULA, QUANTIDADE_MES_ATUAL