CREATE VIEW VW_FUNCIONARIO AS
SELECT MATRICULA AS 'MATRÍCULA', NM_FUNCIONARIO AS 'NOME FUNCIONÁRIO', SEXO AS 'SEXO', 
CD_SETOR AS 'CÓDIGO SETOR' FROM TB_FUNCIONARIO

SELECT * FROM VW_FUNCIONARIO

CREATE VIEW VW_FUNCIONARIO_COMPLETO AS
SELECT F.MATRICULA AS 'MATRÍCULA', F.NM_FUNCIONARIO AS 'NOME FUNCIONÁRIO', F.SEXO AS 'SEXO', 
S.CD_SETOR AS 'CÓDIGO SETOR', S.NM_SETOR AS 'NOME SETOR', D.CD_DEPARTAMENTO AS 'CÓDIGO DEPARTAMENTO', 
D.NM_DEPARTAMENTO AS 'NOME DEPARTAMENTO' FROM TB_FUNCIONARIO F
INNER JOIN TB_SETOR S ON (F.CD_SETOR = S.CD_SETOR)
INNER JOIN TB_DEPARTAMENTO D ON(S.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO) 

SELECT * FROM VW_FUNCIONARIO_COMPLETO

CREATE VIEW VW_SETOR AS
SELECT S.CD_SETOR AS 'CÓDIGO SETOR', S.NM_SETOR AS 'NOME SETOR', S.NM_GERENTE AS 'NOME GERENTE',
D.NM_DEPARTAMENTO AS 'NOME DEPARTAMENTO' FROM TB_SETOR S
INNER JOIN TB_DEPARTAMENTO D ON(S.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO)
WHERE S.CD_SETOR IN
	(
		SELECT F.CD_SETOR FROM TB_FUNCIONARIO F
	)

SELECT * FROM VW_SETOR

CREATE VIEW VW_TOTAL_SOLICITACAO_DEPARTAMENTO AS
SELECT V.[NOME DEPARTAMENTO] AS 'DEPARTAMENTO', COUNT(S.[CD_SOLICITACAO]) AS 'NÚMERO DE SOLICITAÇÕES' FROM TB_SOLICITACAO S, VW_FUNCIONARIO_COMPLETO V
WHERE (V.[MATRÍCULA] = S.[MATRICULA])
GROUP BY V.[NOME DEPARTAMENTO]

SELECT * FROM VW_TOTAL_SOLICITACAO_DEPARTAMENTO

CREATE VIEW VW_DEPARTAMENTO_MAIORES_SOLICITACOES AS 
SELECT V.DEPARTAMENTO FROM VW_TOTAL_SOLICITACAO_DEPARTAMENTO V
WHERE V.[NÚMERO DE SOLICITAÇÕES] = 
	( 
		SELECT MAX(V.[NÚMERO DE SOLICITAÇÕES]) FROM VW_TOTAL_SOLICITACAO_DEPARTAMENTO V
	)

SELECT * FROM VW_DEPARTAMENTO_MAIORES_SOLICITACOES

CREATE TABLE TB_LIVRO 
(
	CD_LIVRO INT NOT NULL,
	NM_LIVRO VARCHAR(40) NOT NULL,
	ISBN INT NOT NULL,
	ANO INT NOT NULL, 
	DATA_CADASTRO DATETIME NOT NULL
)

ALTER TABLE TB_LIVRO ADD CONSTRAINT PK_TB_LIVRO
PRIMARY KEY (CD_LIVRO)

INSERT INTO TB_LIVRO (CD_LIVRO, NM_LIVRO, ISBN, ANO, DATA_CADASTRO)
VALUES (001, 'On The Road', 1253652, 2009, '20140503'),
		(002, 'Fogo Morto', 2514523, 2007, '20150401')

		
INSERT INTO TB_LIVRO (CD_LIVRO, NM_LIVRO, ISBN, ANO, DATA_CADASTRO)
VALUES (002, 'Fogo Morto', 2514523, 2007, '20150401')

CREATE VIEW VW_LIVRO AS
SELECT l.CD_LIVRO AS 'CÓDIGO LIVRO', l.NM_LIVRO AS 'NOME', l.ANO AS 'ANO', l.ISBN AS 'ISBN' 
FROM TB_LIVRO L

SELECT * FROM VW_LIVRO

INSERT INTO VW_LIVRO ([CÓDIGO LIVRO], NOME, ANO, ISBN)
VALUES (003, 'Dom Casmurro', 2015, 2548632)

ALTER TABLE TB_LIVRO 
ALTER COLUMN DATA_CADASTRO DATETIME NULL


