CREATE DATABASE AULA_05
USE AULA_05
/*
A tabela TB_FAIXA_SALARIAL contém as faixas salariais válidas para um determinado
cargo e escolaridade. Criar um procedimento armazenado que, dado um cargo,
escolaridade e salário, verifique se o salário é válido. Observação: Utilize a tabela
TB_FAIXA_SALARIAL no procedimento uma vez que as faixas salariais são alteradas
constantemente

*/


DROP PROCEDURE VALIDAR_SALARIO
CREATE PROCEDURE SP_VALIDAR_SALARIO 
	(@CD_CARGO INT, @SALARIO NUMERIC(10,2), @CD_ESCOLARIDADE INT, @MENSAGEM BIT OUTPUT) AS

IF((SELECT COUNT(*) FROM TB_FAIXASALARIAL F 
  WHERE F.CD_CARGO = @CD_CARGO AND F.CD_ESCOLARIDADE = @CD_ESCOLARIDADE AND (@SALARIO >=  F.MENOR_VALOR AND @SALARIO <= F.MAIOR_VALOR))>0)
	BEGIN
		SET @MENSAGEM = 1
	END
ELSE
	BEGIN
		SET @MENSAGEM = 0
	END


DECLARE @MENSAGEM BIT
EXEC SP_VALIDAR_SALARIO 1,900,1,@MENSAGEM OUTPUT
PRINT @MENSAGEM



/*
Criar um procedimento armazenado utilizando cursores para percorrer a tabela
TB_FUNCIONARIO e, para cada funcionário, verificar, utilizando o procedimento criado
na questão 1, se o salário representa um salário válido para o cargo e escolaridade. Se o
salário não for válido, deve ser incluído um registro na tabela TB_LOG_FUNCIONARIO
informando que o salário para o funcionário não é válido. 

*/

INSERT INTO TB_FUNCIONARIO VALUES
(1,'ALAN',1,1,900),
(2,'EDSON',1,1,800),
(3,'BRENDEL',1,2,1400),
(4,'EDSON',1,2,1300)



SELECT *FROM TB_LOG_FUNCIONARIO;

SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_FAIXASALARIAL

DROP PROCEDURE SP_VALIDACAO
CREATE PROCEDURE SP_VALIDACAO AS
DECLARE @MATRICULA INT,@CD_CARGO INT,@CD_ESCOLARIDADE INT,@SALARIO NUMERIC(10,2)
DECLARE C_VALIDAR_SALARIO CURSOR FOR
SELECT MATRICULA, CD_CARGO,CD_ESCOLARIDADE,SALARIO FROM TB_FUNCIONARIO

OPEN C_VALIDAR_SALARIO 
FETCH C_VALIDAR_SALARIO INTO @MATRICULA,@CD_CARGO,@CD_ESCOLARIDADE,@SALARIO
WHILE(@@FETCH_STATUS = 0)
	BEGIN
		DECLARE @MENSAGEM INT
		EXEC SP_VALIDAR_SALARIO @CD_CARGO,@SALARIO,@CD_ESCOLARIDADE,@MENSAGEM OUTPUT
		IF(@MENSAGEM = 0)
			BEGIN
				INSERT INTO TB_LOG_FUNCIONARIO VALUES(@MATRICULA,'SALARIO INVALIDO', GETDATE())
			END
		FETCH C_VALIDAR_SALARIO INTO @MATRICULA,@CD_CARGO,@CD_ESCOLARIDADE,@SALARIO
			
	END
CLOSE C_VALIDAR_SALARIO
DEALLOCATE C_VALIDAR_SALARIO



EXEC SP_VALIDACAO
