--CRIAÇÃO DO BANCO
CREATE DATABASE AULA_04
USE AULA_04


-- Criar uma tabela TB_CLIENTE com a seguinte estrutura:

CREATE TABLE TB_CLIENTE(
MATRICULA INT NOT NULL,
NOME VARCHAR(40) NOT NULL,
TELEFONE VARCHAR(10) NOT NULL
)
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_TB_CLIENTE PRIMARY KEY(MATRICULA);


/*
Criar um procedimento armazenado, SP_INCLUI_CLIENTE, para incluir um novo
Cliente. O procedimento deve apresentar como parâmetros de entrada a Matrícula, o
Nome e o Telefone do Cliente a ser incluído.
*/
CREATE PROCEDURE SP_INCLUI_CLIENTE 
(@MATRICULA INT,@NOME VARCHAR(40), @TELEFONE VARCHAR(10)) AS
INSERT TB_CLIENTE (MATRICULA,NOME,TELEFONE) VALUES
(@MATRICULA,@NOME,@TELEFONE)





EXEC SP_INCLUI_CLIENTE 1,'ALAN PASSOS', '9087654575'
EXEC SP_INCLUI_CLIENTE 2,'ANDRE VINICIUS', '7897654575'
EXEC SP_INCLUI_CLIENTE 3,'EDSON LIMA', '0007654575'
EXEC SP_INCLUI_CLIENTE 4,'BRENDEL SANTOS', '1117654575'
EXEC SP_INCLUI_CLIENTE 5,'IURY BATISTA', '8887654575'


/*
Criar um procedimento armazenado, SP_REMOVE_CLIENTE, para remover um Cliente
cadastrado. O procedimento deve apresentar como parâmetro de entrada a Matrícula do
Cliente a ser removido.
*/


CREATE PROCEDURE SP_REMOVE_CLIENTE 
(@MATRICULA INT) AS
DELETE TB_CLIENTE  WHERE MATRICULA = @MATRICULA 

EXEC SP_REMOVE_CLIENTE 1

 /*
Alterar os procedimentos dos itens 2 e 3 para incluir um parâmetro de saída a fim de
informar o resultado da execução do procedimento.
*/

-- PROCEDIEMNTO 1
ALTER PROCEDURE SP_INCLUI_CLIENTE 
(@MATRICULA INT,@NOME VARCHAR(40), @TELEFONE VARCHAR(10), @MENSAGEM VARCHAR(40) OUTPUT) AS

INSERT TB_CLIENTE (MATRICULA,NOME,TELEFONE) VALUES
(@MATRICULA,@NOME,@TELEFONE)
IF @@ERROR = 0
	SET @MENSAGEM = 'CLIENTE INCLUIDO'
ELSE 
	SET @MENSAGEM = 'CLIENTE NÃO INCLUIDO'

DECLARE @MENSAGEM VARCHAR(40)
EXEC SP_INCLUI_CLIENTE 1,'ALAN PASSOS', '9087654575',@MENSAGEM OUTPUT
EXEC SP_INCLUI_CLIENTE 2,'ANDRE VINICIUS', '7897654575',@MENSAGEM OUTPUT
EXEC SP_INCLUI_CLIENTE 3,'EDSON LIMA', '0007654575',@MENSAGEM OUTPUT
EXEC SP_INCLUI_CLIENTE 4,'BRENDEL SANTOS', '1117654575',@MENSAGEM OUTPUT
EXEC SP_INCLUI_CLIENTE 5,'IURY BATISTA', '8887654575',@MENSAGEM OUTPUT
PRINT @MENSAGEM

-- VAI ACONTECER ERRO
DECLARE @MENSAGEM VARCHAR(40)
EXEC SP_INCLUI_CLIENTE NULL,'ALAN PASSOS', '9087654575',@MENSAGEM OUTPUT
PRINT @MENSAGEM

-- PROCEDIEMNTO 2
ALTER PROCEDURE SP_REMOVE_CLIENTE 
(@MATRICULA INT, @MENSAGEM VARCHAR(40) OUTPUT) AS
DELETE TB_CLIENTE  WHERE MATRICULA = @MATRICULA 
SET @MENSAGEM  = 'REMOVIDO COM SUCESSO'

DECLARE @MENSAGEM VARCHAR(40)
EXEC SP_REMOVE_CLIENTE 1,@MENSAGEM OUTPUT
PRINT @MENSAGEM

/*
Criar um procedimento armazenado, SP_ALTERA_CLIENTE, para alterar as
informações (Nome e Telefone) de um Cliente cadastrado. O procedimento deve
apresentar como parâmetros de entrada a Matrícula, o Nome e o Telefone do Cliente.*/

--@@ROWCOUNT SABER QUANTAS LINHAS FORA AFETADAS OU ATUALIZADAS
CREATE PROCEDURE SP_ALTERA_CLIENTE 
(@MATRICULA INT , @NOME VARCHAR(40), @TELEFONE VARCHAR(10), @MENSAGEM VARCHAR(40)OUTPUT) AS

UPDATE  TB_CLIENTE SET NOME =  @NOME , TELEFONE = @TELEFONE WHERE MATRICULA = @MATRICULA
IF @@ERROR = 0
	BEGIN
				SET @MENSAGEM = 'ALTERADO COM SUCESSO'
	END 
ELSE
	BEGIN
		SET @MENSAGEM = 'ERRO AO ALTERAR DADOS'	
	END

DECLARE @MENSAGEM VARCHAR(40)
EXEC SP_ALTERA_CLIENTE 10,'TAZ MANIA','9088765616',@MENSAGEM OUTPUT
PRINT @MENSAGEM


/*
Alterar o procedimento SP_ALTERA_CLIENTE para adicionar a seguinte
funcionalidade: Se o valor do parâmetro passado for nulo (NULL) o atributo
correspondente não deve ser modificado

*/
-- PRIMAIERA 
ALTER PROCEDURE SP_ALTERA_CLIENTE 
(@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(10), @MENSAGEM VARCHAR(40) OUTPUT) AS
IF(@NOME IS NOT NULL) 
	BEGIN 
		UPDATE TB_CLIENTE SET NOME = @NOME WHERE MATRICULA = @MATRICULA
		SET @MENSAGEM = 'NOME ALTERADO'
	END
IF(@TELEFONE IS NOT NULL )
	BEGIN
	 	UPDATE TB_CLIENTE SET TELEFONE = @TELEFONE WHERE MATRICULA = @MATRICULA
		SET @MENSAGEM = 'TELEFONE ALTERADO'
	END

DECLARE @MENSAGEM VARCHAR(40)
EXEC SP_ALTERA_CLIENTE 10,'ALAN',NULL, @MENSAGEM OUTPUT
PRINT @MENSAGEM


