/*
Criar um procedimento para calcular o aumento de SALÁRIO a ser dado em função do tempo de
serviço em uma determinada empresa. O procedimento deve apresentar como parâmetros de
entrada o Ano de Admissão e o Salário Atual, e como parâmetro de saída o Salário após o
aumento: 
*/


ALTER PROCEDURE CALCULO_SALARIO
(@ANO_ADMISSAO DATE, @SALARIO NUMERIC(10,2), @SALARIO_AUMENTO NUMERIC(10,2) OUTPUT) AS
IF( @ANO_ADMISSAO < '2000')
   BEGIN
		SET @SALARIO_AUMENTO = @SALARIO + ((@SALARIO *30)/100)
   END
ELSE 
   BEGIN
		IF(@ANO_ADMISSAO >= '2000' AND @ANO_ADMISSAO <='2004')
			BEGIN
				SET @SALARIO_AUMENTO = @SALARIO + (@SALARIO *20)/100
			END
		ELSE
			BEGIN
				SET @SALARIO_AUMENTO = @SALARIO + (@SALARIO *10)/100
			END
	END


	DECLARE @SALARIO_AUMENTO NUMERIC(10,2)
EXEC CALCULO_SALARIO '1999',100,@SALARIO_AUMENTO OUTPUT
PRINT @SALARIO_AUMENTO


/*
Criar uma tabela TB_FUNCIONARIO com os seguintes atributos: MATRICULA,
NM_FUNCIONARIO, ANO_ADMISSAO, SALARIO 


*/
DROP TABLE TB_FUNCIONARIO

CREATE TABLE TB_FUNCIONARIO(
MATRICULA INT NOT NULL,
NM_FUNCIONARIO VARCHAR(45) NOT NULL,
ANO_ADMISSAO DATE NOT NULL,
SALARIO NUMERIC(10,2) NOT NULL
)

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT PK_TB_FUNCIONARIO PRIMARY KEY (MATRICULA)

INSERT INTO TB_FUNCIONARIO VALUES
(1,'ALAN','2000',100),
(2,'BRENDEL','1999',200),
(3,'EDSON','2009',50),
(4,'IURY','2004',200)

SELECT * FROM TB_FUNCIONARIO
/*
Criar um procedimento, utilizando cursores, para percorrer a tabela TB_FUNCIONARIO e
atualizar o SALARIO dos funcionários através do procedimento criado na questão 1. 

*/
DROP PROCEDURE ATUALIZAR_SALARIO
CREATE PROCEDURE ATUALIZAR_SALARIO AS
DECLARE @MATRICULA INT, @SALARIO NUMERIC(10,2), @ANO DATE
DECLARE C_ATUALIZAR_SALARIO CURSOR FOR 
SELECT MATRICULA, SALARIO, ANO_ADMISSAO FROM TB_FUNCIONARIO

OPEN C_ATUALIZAR_SALARIO
FETCH C_ATUALIZAR_SALARIO INTO @MATRICULA,@SALARIO,@ANO
WHILE(@@FETCH_STATUS=0)
	BEGIN
		DECLARE @SALARIO_AUMENTO NUMERIC(10,2)
		EXEC CALCULO_SALARIO @ANO,@SALARIO,@SALARIO_AUMENTO OUTPUT
		 
		UPDATE TB_FUNCIONARIO SET SALARIO = @SALARIO_AUMENTO WHERE MATRICULA = @MATRICULA
			FETCH C_ATUALIZAR_SALARIO INTO @MATRICULA,@SALARIO,@ANO
	END
CLOSE C_ATUALIZAR_SALARIO
DEALLOCATE C_ATUALIZAR_SALARIO

EXEC ATUALIZAR_SALARIO

SELECT * FROM TB_FUNCIONARIO