CREATE TABLE TB_FUNCIONARIO
(
	MATRICULA INT NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	TELEFONE VARCHAR(9),
	ENDERECO VARCHAR(40),
	SALARIO NUMERIC(10,2),
	PENDENCIA VARCHAR(16)
)

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT PK_TB_FUNCIONARIO
PRIMARY KEY (MATRICULA)

--Método está realizando o procedimento de forma duplicada. Não sei o que porque
-- Ao dar update utilizando cursores, sempre passar o parametro da matricula e utilizar o where para
--fazer a checagem
ALTER PROCEDURE SP_VERIFICA_PENDENCIA AS
DECLARE @MATRICULA INT, @TELEFONE VARCHAR(9), @ENDERECO VARCHAR(40), @SALARIO NUMERIC(10,2)
DECLARE C_PENDENCIA CURSOR FOR
SELECT F.MATRICULA, F.TELEFONE, F.ENDERECO, F.SALARIO FROM TB_FUNCIONARIO F
OPEN C_PENDENCIA 
FETCH C_PENDENCIA INTO @MATRICULA, @TELEFONE, @ENDERECO, @SALARIO
WHILE (@@FETCH_STATUS = 0)
	BEGIN

		IF (@TELEFONE IS NOT NULL) AND (@ENDERECO IS NOT NULL) AND (@SALARIO IS NOT NULL)
			BEGIN
				PRINT 'ENTROU HEIN'
				UPDATE TB_FUNCIONARIO SET PENDENCIA = 'SEM PENDÊNCIA' WHERE @MATRICULA = MATRICULA
			END
		ELSE
			BEGIN
				PRINT 'ENTROU ELSE'
				UPDATE TB_FUNCIONARIO SET PENDENCIA = 'EXISTE PENDÊNCIA'WHERE @MATRICULA = MATRICULA
			END
		
		FETCH C_PENDENCIA INTO @MATRICULA, @TELEFONE, @ENDERECO, @SALARIO
	END
CLOSE C_PENDENCIA
DEALLOCATE C_PENDENCIA 


INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, TELEFONE, ENDERECO, SALARIO)
VALUES (001, 'JOSE', '74128523', 'RUA NOVA RUA', 1589.25)

INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, ENDERECO, SALARIO)
VALUES (002, 'MARIA', 'RUA OUTRA RUA', 5986.25)

SELECT * FROM TB_FUNCIONARIO

EXEC SP_VERIFICA_PENDENCIA