/*
2.Criar    uma    tabela    TB_FUNCIONARIO    com    os    seguintes    atributos:    MATRICULA, 
NM_FUNCIONARIO, ANO_ADMISSAO, SALARIO 
*/
CREATE TABLE TB_FUNCIONARIO_DOIS
(
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(50) NOT NULL,
	ANO_ADMISSAO INT NOT NULL,
	SALARIO NUMERIC(10,2) NOT NULL
)

ALTER TABLE TB_FUNCIONARIO_DOIS ADD CONSTRAINT PK_TB_FUNCINARIO_DOIS 
PRIMARY KEY (MATRICULA)

/*
1. Criar um procedimento para calcular o aumento de SALÁRIO a ser dado em função do tempo de 
serviço  em  uma  determinada  empresa.  O  procedimento  deve  apresentar  como  parâmetros  de 
entrada  o  Ano  de  Admissão  e  o  Salário  Atual,  e  como  parâmetro  de
saída  o  Salário  após  o 
aumento: 
*/
CREATE PROCEDURE SP_CALC_AUMENTO_SALARIO (@ANO_ADMISSAO INT, @SALARIO_ATUAL NUMERIC(10,2),
											@MENSAGEM NUMERIC(10,2) OUTPUT) AS
IF (@ANO_ADMISSAO < 2000)
	BEGIN
		SET @MENSAGEM = @SALARIO_ATUAL + (@SALARIO_ATUAL * 0.30)
	END
ELSE IF (@ANO_ADMISSAO >= 2000 AND @ANO_ADMISSAO <= 2004)
	BEGIN
		SET @MENSAGEM = @SALARIO_ATUAL + (@SALARIO_ATUAL * 0.20)
	END
ELSE 
	BEGIN
		SET @MENSAGEM = @SALARIO_ATUAL + (@SALARIO_ATUAL * 0.10)
	END

-------------------------------------------------------------
DECLARE @MENSAGEM NUMERIC(10,2)
EXEC SP_CALC_AUMENTO_SALARIO 2005, 1000, @MENSAGEM OUTPUT
PRINT @MENSAGEM

/*
3. Criar  um  procedimento, utilizando  cursores,  para  percorrer  a  tabela  TB_FUNCIONARIO  e 
atualizar o SALARIO dos funcionários através do procedimento criado na questão 1. 
*/
CREATE PROCEDURE SP_ATUALIZA_SALARIO_TB_FUNCIONARIO AS
DECLARE @MATRICULA INT, @ANO INT, @SALARIO NUMERIC(10,2), @MENSAGEM NUMERIC(10,2)
DECLARE C_ATUALIZA CURSOR FOR
SELECT F.MATRICULA, F.ANO_ADMISSAO, F.SALARIO FROM TB_FUNCIONARIO_DOIS F

OPEN C_ATUALIZA
FETCH C_ATUALIZA INTO @MATRICULA, @ANO, @SALARIO
WHILE (@@FETCH_STATUS = 0)
	BEGIN
	EXEC SP_CALC_AUMENTO_SALARIO @ANO, @SALARIO, @MENSAGEM OUTPUT
	UPDATE TB_FUNCIONARIO_DOIS SET SALARIO = @MENSAGEM WHERE MATRICULA = @MATRICULA

	FETCH C_ATUALIZA INTO @MATRICULA, @ANO, @SALARIO
	END
CLOSE C_ATUALIZA
DEALLOCATE C_ATUALIZA

------------------------------------------------
INSERT INTO TB_FUNCIONARIO_DOIS
VALUES (001, 'JÓSE', 2000, 1000),
		(002, 'MARTA', 1994, 3600),
		(003, 'LAURA', 2006, 1500)


--------------------------------------------------
SELECT * FROM TB_FUNCIONARIO_DOIS

EXEC SP_ATUALIZA_SALARIO_TB_FUNCIONARIO