alter PROCEDURE SP_FORMALIZA_PADRAO (@CAMPO VARCHAR(4), @CAMPO_FORMATADO VARCHAR(4) OUTPUT) AS
DECLARE @TAMANHO_POST INT, @ZEROS VARCHAR(3)

		SET @CAMPO = LTRIM(RTRIM(@CAMPO))
		SET @CAMPO = REPLACE(@CAMPO, '	', '')
		SET @CAMPO = REPLACE(@CAMPO, '	', '')
		SET @TAMANHO_POST = LEN(@CAMPO)
		SET @ZEROS = REPLICATE('0', (4 - @TAMANHO_POST))
		SET @CAMPO_FORMATADO = CONCAT(@ZEROS, @CAMPO)

		

ALTER PROCEDURE SP_POVOA_TABELA_PRODUTOS_AUXILIAR AS
DECLARE @COD_PRODUTO_SP INT, @DESCRICAO_SP VARCHAR(12), @COD_EMBALAGEM_SP VARCHAR(4), @COD_EMBALAGEM_FORMATADO_SP VARCHAR(4)
DECLARE C_POVOA_PRODUTOS_SP CURSOR FOR
SELECT P.COD_PRODUTO, P.DESCRICAO, P.COD_EMBALAGEM FROM TB_PRODUTO_EXE13 P

OPEN C_POVOA_PRODUTOS_SP
FETCH C_POVOA_PRODUTOS_SP INTO @COD_PRODUTO_SP, @DESCRICAO_SP, @COD_EMBALAGEM_SP

WHILE (@@FETCH_STATUS = 0)

	BEGIN
		EXEC SP_FORMALIZA_PADRAO @COD_EMBALAGEM_SP, @COD_EMBALAGEM_FORMATADO_SP OUTPUT
		INSERT INTO TB_PRODUTO_AUX_EXE13
		VALUES (@COD_PRODUTO_SP, @DESCRICAO_SP, @COD_EMBALAGEM_FORMATADO_SP)
	
		FETCH C_POVOA_PRODUTOS_SP INTO @COD_PRODUTO_SP, @DESCRICAO_SP, @COD_EMBALAGEM_SP
	END
CLOSE C_POVOA_PRODUTOS_SP
DEALLOCATE C_POVOA_PRODUTOS_SP

EXEC SP_POVOA_TABELA_PRODUTOS_AUXILIAR

SELECT * FROM TB_PRODUTO_AUX_EXE13
DELETE FROM TB_PRODUTO_AUX_EXE13