SET DATEFORMAT YMD

CREATE TABLE TB_VENDAS_EXE12 (
	CD_VENDA INT NOT NULL IDENTITY(1,1),
	DT_VENDA DATETIME NOT NULL,
	MATRICULA INT NOT NULL,
	CD_PRODUTO INT NOT NULL,
	QUANTIDADE NUMERIC(10,2) NOT NULL 
)

INSERT INTO TB_VENDAS_EXE12 
VALUES ('2009-01-01', 10, 1001, 50.00),
		('2009-01-01', 10, 1002, 50.00),
		('2009-02-01', 10, 1001, 150.00),
		('2009-01-01', 30, 1001, 200.00),
		('2009-01-01', 30, 1001, 100.00),
		('2009-02-01', 30, 1001, 150.00),
		('2009-05-01', 40, 1002, 100.00),
		('2009-05-10', 40, 1002, 200.00),
		('2009-07-01', 40, 1001, 250.00)

CREATE TABLE TB_VENDAS_MENSAL_EXE12(
	
	MATRICULA INT NOT NULL,
	ANO INT NOT NULL,
	MES INT NOT NULL,
	MES_ATUAL NUMERIC(10,2),
	MES_ANTERIOR NUMERIC(10,2) NOT NULL,
	VARIACAO NUMERIC(6,6) NOT NULL
)

ALTER PROCEDURE SP_CALCULA_VALOR_MES_ATUAL_EXE12 (@MATRICULA INT, @MES INT, @ANO INT,
												 @VALOR NUMERIC(10,2) OUTPUT) AS

DECLARE @MATRICULA_A INT, @MES_A INT, @ANO_A INT, @QUANTIDADE_A NUMERIC(10,2), @QUANTIDADE_TOTAL NUMERIC(10,2) = 0.0
DECLARE C_CALCULO_TOTAL CURSOR FOR
SELECT V.MATRICULA, MONTH(V.DT_VENDA), YEAR(V.DT_VENDA), V.QUANTIDADE FROM TB_VENDAS_EXE12 V

OPEN C_CALCULO_TOTAL
FETCH C_CALCULO_TOTAL INTO @MATRICULA_A, @MES_A, @ANO_A, @QUANTIDADE_A

WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF (@MATRICULA_A = @MATRICULA AND @MES_A = @MES AND @ANO_A = @ANO)
			BEGIN
				
				SET @QUANTIDADE_TOTAL = @QUANTIDADE_TOTAL + @QUANTIDADE_A
			END

		FETCH C_CALCULO_TOTAL INTO @MATRICULA_A, @MES_A, @ANO_A, @QUANTIDADE_A
	END
CLOSE C_CALCULO_TOTAL
DEALLOCATE C_CALCULO_TOTAL 

ALTER PROCEDURE SP_CALCULA_VARIACAO_VENDA_EXE12 (@MATRICULA INT, @MES INT, @ANO INT, @QUANTIDADE NUMERIC(10,2),
												 @VALOR NUMERIC(10,2) OUTPUT, @QUANTIDADE_MES_ANTERIOR NUMERIC(10,2) OUTPUT) AS

SET @QUANTIDADE_MES_ANTERIOR = 0.0
DECLARE @MES_SP INT = @MES, @ANO_SP INT = @ANO
IF (@MES_SP = 1)
	BEGIN
		SET @MES_SP = 13
		SET @ANO_SP = @ANO_SP - 1
	END
DECLARE @MATRICULA_A INT, @MES_A INT, @ANO_A INT, @QUANTIDADE_A NUMERIC(10,2)
DECLARE C_CALCULO_VENDA CURSOR FOR
SELECT V.MATRICULA, MONTH(V.DT_VENDA), YEAR(V.DT_VENDA), V.QUANTIDADE FROM TB_VENDAS_EXE12 V

OPEN C_CALCULO_VENDA
FETCH C_CALCULO_VENDA INTO @MATRICULA_A, @MES_A, @ANO_A, @QUANTIDADE_A

WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF (@MATRICULA_A = @MATRICULA AND @MES_A = (@MES_SP - 1) AND @ANO_A = @ANO_SP)
			BEGIN
				
				SET @QUANTIDADE_MES_ANTERIOR = @QUANTIDADE_MES_ANTERIOR + @QUANTIDADE_A
			END

		FETCH C_CALCULO_VENDA INTO @MATRICULA_A, @MES_A, @ANO_A, @QUANTIDADE_A
	END

IF (@QUANTIDADE_MES_ANTERIOR <> 0.0)
	SET @VALOR = (@QUANTIDADE - @QUANTIDADE_MES_ANTERIOR) / @QUANTIDADE_MES_ANTERIOR
ELSE
	SET @VALOR = 0.0

CLOSE C_CALCULO_VENDA
DEALLOCATE C_CALCULO_VENDA 

DECLARE @VALOR NUMERIC(10,2), @QUANTIDADE numeric(10,2)
EXEC SP_CALCULA_VARIACAO_VENDA_EXE12 40, 07, 2009, 250, @VALOR OUTPUT, @QUANTIDADE OUTPUT
PRINT @QUANTIDADE
PRINT @VALOR




ALTER PROCEDURE SP_POVOA_TABELA_VENDAS_MES_EXE12 AS
DECLARE @MATRICULA INT, @MES_ATUAL INT, @ANO INT, @QUANTIDADE NUMERIC(10,2), @MES_AUX INT, @MATRICULA_AUX INT
DECLARE @VARIACAO NUMERIC (10,2), @QUANTIDADE_MES_ATUAL NUMERIC(10,2), @QUANTIDADE_MES_ANTERIOR NUMERIC (10,2)
DECLARE C_TABELA_VENDAS CURSOR FOR
SELECT V.MATRICULA, MONTH(V.DT_VENDA), YEAR(V.DT_VENDA), V.QUANTIDADE FROM TB_VENDAS_EXE12 V

OPEN C_TABELA_VENDAS
FETCH C_TABELA_VENDAS INTO @MATRICULA, @MES_ATUAL, @ANO, @QUANTIDADE
SET @MES_AUX = 0
SET @MATRICULA_AUX = 0
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF (@MES_ATUAL <> @MES_AUX)
		BEGIN
			EXEC SP_CALCULA_VALOR_MES_ATUAL_EXE12 @MATRICULA, @MES_ATUAL, @ANO, @QUANTIDADE_MES_ATUAL OUTPUT
			PRINT @QUANTIDADE_MES_ATUAL
			EXEC SP_CALCULA_VARIACAO_VENDA_EXE12 @MATRICULA, @MES_ATUAL, @ANO, @QUANTIDADE_MES_ATUAL, @VARIACAO OUTPUT, 
															@QUANTIDADE_MES_ANTERIOR OUTPUT

			INSERT INTO TB_VENDAS_MENSAL_EXE12 
			VALUES (@MATRICULA, @ANO, @MES_ATUAL, @QUANTIDADE_MES_ATUAL, @QUANTIDADE_MES_ANTERIOR, @VARIACAO)
			SET @MES_AUX = @MES_ATUAL
			SET @MATRICULA_AUX = @MATRICULA
		END
		FETCH C_TABELA_VENDAS INTO @MATRICULA, @MES_ATUAL, @ANO, @QUANTIDADE
	END

CLOSE C_TABELA_VENDAS
DEALLOCATE C_TABELA_VENDAS

SELECT * FROM TB_VENDAS_EXE12
SELECT * FROM TB_VENDAS_MENSAL_EXE12

EXEC SP_POVOA_TABELA_VENDAS_MES_EXE12
SELECT * FROM TB_VENDAS_EXE12
SELECT * FROM TB_VENDAS_MENSAL_EXE12

DELETE FROM TB_VENDAS_MENSAL_EXE12

