--a)
SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_TEMPO ON (ID_TEMPO = ID_DATA_ABERTURA)
WHERE DATA = GETDATE()

SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_TEMPO ON (ID_TEMPO = ID_DATA_ABERTURA)
WHERE MONTH(DATA) = 02 OR ....


--b)
SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_TEMPO ON (ID_TEMPO = ID_DATA_FECHAMENTO)
WHERE DATA > '2009-01-01' AND DATA < '2012-01-01'

--C)
SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_TEMPO ON (ID_TEMPO = ID_DATA_ANDAMENTO)
WHERE DATA = GETDATE()

--d)
SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_TEMPO ON (ID_TEMPO = ID_DATA_ANDAMENTO)
WHERE DIA = '...'

-E)
SELECT NM_DEPARTAMENTO, SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_DEPARTAMENTO ON (ID_DETARTAMENTO = ID_DEPARTAMENTO)
GROUP BY NM_DEPARTAMENTO

--F)
SELECT PRIORIDADE, SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_PRIORIDADE ON (ID_PRIORIDADE = ID_PRIORIRADE)
INNER JOIN D_STATUS ON (ID_STATUS = ID_STATUS)
WHERE NM_STATUS = 'ABERTO'
GROUP BY PRIORIDADE

--I)
SELECT FUNCIONARIO, SUM(QUANTIDADE) FROM FATO_INCIDENTES
INNER JOIN D_USUARIO ON (ID_USUARIO = ID_ATENDENTE)
INNER JOIN D_STATUS ON (ID_STATUS = ID_STATUS)
WHERE NM_STATUS = 'EM ANDAMENTO'
GROUP BY FUNCIONARIO

--K
SELECT DEPARTAMENTO, SUM(QUANTIDADE) FROM FATO_INCIDENTE
INNER JOIN D_DEPARTAMENTO ON (ID_DEPARTAMENTO = ID_DEPARTAMENTO)
INNER JOIN D_USUARIO ON (ID_USUARIO = ID_SOLICITANTE)
INNER JOIN D_STATUS ON (ID_STATUS = ID_STATUS)
WHERE NM_STATUS = 'ABERTO'
GROUP BY DEPARTAMENTO

--M)
SELECT AVG(TEMPO_ABERTURA_ANDAMENTO) FROM FATO_INCIDENTE
INNER JOIN D_NIVEL (ID_NIVEL = ID_NIVEL)
WHERE NM_NIVEL = 'PRIMEIRO NIVEL'

--P
SELECT SUM(QUANTIDADE) FROM FATO_INCIDENTE
WHERE TEMPO_ABERTURA_FECHAMENTO > TEMPO_ESTIMADO

