DROP TABLE TB_FUNCIONARO_SE;
DROP TABLE TB_FUNCIONARIO_AL;
DROP TABLE TB_FUNCIONARIO_PB;

CREATE DATABASE AULA_03

CREATE TABLE TB_FUNCIONARIO_SE(
MATRICULA INT NOT NULL,
NM_FUNCIONARIO VARCHAR(40) NOT NULL,
ESTADO CHAR(2) CHECK (ESTADO = 'SE')  NOT NULL ,
SALARIO NUMERIC(10,2)
);

ALTER TABLE TB_FUNCIONARIO_SE ADD CONSTRAINT PK_TB_FUNCIONARIO_SE PRIMARY KEY(MATRICULA,ESTADO);

CREATE TABLE TB_FUNCIONARIO_AL(
MATRICULA INT NOT NULL,
NM_FUNCIONARIO VARCHAR(40) NOT NULL,
ESTADO CHAR(2) CHECK (ESTADO = 'AL') NOT NULL,
SALARIO NUMERIC(10,2) )

ALTER TABLE TB_FUNCIONARIO_AL ADD CONSTRAINT PK_TB_FUNCIONARIO_AL PRIMARY KEY(MATRICULA,ESTADO);

CREATE TABLE TB_FUNCIONARIO_PB(
MATRICULA INT NOT NULL,
NM_FUNCIONARIO VARCHAR(40) NOT NULL,
ESTADO CHAR(2) CHECK (ESTADO = 'PB') NOT NULL,
SALARIO NUMERIC(10,2) )

ALTER TABLE TB_FUNCIONARIO_PB ADD CONSTRAINT PK_TB_FUNCIONARIO_PB PRIMARY KEY(MATRICULA,ESTADO);
SELECT * FROM VW_FUNCIONARIOS


CREATE VIEW VW_FUNCIONARIOS AS
SELECT * FROM TB_FUNCIONARIO_AL 
UNION ALL
SELECT * FROM TB_FUNCIONARIO_PB
UNION ALL
SELECT * FROM TB_FUNCIONARIO_SE


INSERT INTO VW_FUNCIONARIOS VALUES 
(1,'ALAN','SE',900)

SELECT * FROM TB_FUNCIONARIO_PB

UPDATE VW_FUNCIONARIOS SET ESTADO = 'PB' WHERE MATRICULA = 1
SELECT * FROM TB_FUNCIONARIO_PB