-- CRIANDO BANCO DE DADOS DB_EMPRESA_LOCADORA
CREATE DATABASE db_empresa_locadora;
-- USANDO O BANCO DE DADOS CRIADO
USE  db_empresa_locadora;

-- CRIANDO TABELA TB_DVD
CREATE TABLE TB_DVD(

cd_dvd INT NOT NULL,
titulo VARCHAR(40) NOT NULL,
categoria VARCHAR(40) NOT NULL,
);

ALTER TABLE TB_DVD ADD CONSTRAINT PK_TB_DVD PRIMARY KEY (cd_dvd)



-- ALTER TABLE TB_DVD ALTER COLUMN cd_dvd INT NOT NULL;
-- CRIANDO TABELA TB_CLIENTE
CREATE TABLE TB_CLIENTE(
cd_cliente INT NOT NULL,
nm_cliente VARCHAR(50) NOT NULL,

);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_TB_CLIENTE PRIMARY KEY (cd_cliente)


--  CRIANDO TABELA TB_LOCACAO
CREATE TABLE TB_LOCACAO(
cd_cliente INT NOT NULL,
cd_dvd INT NOT NULL,
valor DECIMAL(10,2) NOT NULL,
dt_alocacao DATE NOT NULL DEFAULT GETDATE(),
dt_devolucao DATE NULL,


);

ALTER TABLE TB_LOCACAO ADD CONSTRAINT PK_LOCACAO PRIMARY KEY (cd_dvd,cd_cliente)
ALTER TABLE TB_LOCACAO ADD CONSTRAINT FK_TB_DVD FOREIGN KEY (cd_dvd) REFERENCES TB_DVD
ALTER TABLE TB_LOCACAO ADD CONSTRAINT FK_TB_CLIENTE FOREIGN KEY (cd_cliente) REFERENCES TB_CLIENTE

-- RENOMENADO UMA TABELA
-- exec sp_rename LOCACAO , TB_LOCACAO;

